package terminalbuffer.models

enum class Color {
    DEFAULT_FG, DEFAULT_BG, BLACK, WHITE, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN,
    BRIGHT_BLACK, BRIGHT_RED, BRIGHT_GREEN, BRIGHT_YELLOW,
    BRIGHT_BLUE, BRIGHT_MAGENTA, BRIGHT_CYAN, BRIGHT_WHITE
}